# Build stage
FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
ARG VITE_CLERK_PUBLISHABLE_KEY
ARG VITE_AUTOMATOS_WORKSPACE_ID
ARG VITE_AUTOMATOS_PUBLIC_KEY
ARG VITE_AUTOMATOS_CHAT_AGENT_ID
ENV VITE_CLERK_PUBLISHABLE_KEY=$VITE_CLERK_PUBLISHABLE_KEY
ENV VITE_AUTOMATOS_WORKSPACE_ID=$VITE_AUTOMATOS_WORKSPACE_ID
ENV VITE_AUTOMATOS_PUBLIC_KEY=$VITE_AUTOMATOS_PUBLIC_KEY
ENV VITE_AUTOMATOS_CHAT_AGENT_ID=$VITE_AUTOMATOS_CHAT_AGENT_ID
RUN npm run build

# Production stage — Node serves static SPA + contact API
FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --omit=dev
COPY server.js ./
COPY --from=build /app/dist ./dist
ENV PORT=80
EXPOSE 80
CMD ["node", "server.js"]
